config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  devise_for :users
  resources :logros
  resources :postulacions

  resources :gauchadas
  resources :preguntums
  resources :preguntas
  get '/misgauchadas', to: 'gauchadas#misgauchadas'

  resources :gauchadas do
    post "calificar", on: :member
    get "misgauchadas", on: :collection
  end
  get '/mispostulaciones', to: 'gauchadas#mispostulaciones'
  get '/gauchadascumplidas', to: 'gauchadas#cumplidas'

  get '/realizar', to: 'gauchadas#marcar'
  root 'gauchadas#index'
  get '/comprar_puntos/edit', to: 'comprar_puntos#edit'
  get '/comprar_puntos/actualizar', to: 'comprar_puntos#actualizar'
  get '/buscar', to: 'gauchadas#buscar'
  get '/postulacion/aceptar', to: 'postulacions#aceptar'
  get '/postulacion/rechazar', to: 'postulacions#rechazar'
  get '/reporteusuario', to: 'comprar_puntos#reporteusuario'
  get '/reporteganancia', to: 'comprar_puntos#reporteganancia'
  get '/buscarpagos', to: 'comprar_puntos#buscarpagos'
  post '/comentario', to: 'pregunta#create'
  post '/respuesta', to: 'pregunta#responder'

end

app/models/gauchada.rb
class Gauchada < ActiveRecord::Base
  has_many :pregunta
  has_many :postulacions
  has_many :comentarios
  belongs_to :usuario
  validates_associated :usuario
  validates :titulo, presence: true
  validates :descripcion, presence: true
  validates :ubicacion, presence: true
 validates :imagen, format: { with: /.*/ }
  default_scope -> { order("created_at desc") }

def self.search(search)
  where("ubicacion ILIKE ? OR titulo ILIKE ? OR descripcion ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
end
end

app/controllers/gauchadas_controller.rb
class GauchadasController < ApplicationController

  def new
  end

  def default
  end

  def index
      @gauchadas=Gauchada.all
  end

  def show
    @gauchada = Gauchada.find(params[:id])
  end

  def create
# El método create recibe params = { gauchada: { titulo: string, ubicacion: string, descripcion: string, foto } }
    @gauchada =Gauchada.new(params.require(:gauchada).permit(:titulo,:ubicacion,:descripcion,:imagen,:user_id))
    @user =current_user
    @gauchada.user_id = @user.id
    if @gauchada.save
      @user.puntos_para_gauchadas -=1
      @user.save
      flash[:notice] = "Gauchada creada correctamente"
      redirect_to (gauchadas_path)
    else
      flash[:notice] = "No se pudo crear la gauchada"
      render 'new'
    end
  end


  def new
  if(current_user.puntos_para_gauchadas <= 0)
    flash[:notice] = "No tiene suficientes puntos para pedir una gauchada"
    redirect_to(comprar_puntos_edit_path)
  else
  @gauchada = Gauchada.new
end

  end

  def edit
  @gauchada= Gauchada.find(params[:id])
  end


  def update
    @gauchada= Gauchada.find(params[:id])
    if @gauchada.update_attributes(params.require(:gauchada).permit(:titulo,:ubicacion,:descripcion,:imagen))
      flash[:notice] = "Gauchada modificada correctamente"
      redirect_to (gauchadas_path)
    else
      flash[:notice] = "No se pudo modificar la gauchada"
      render 'edit'
    end
  end

  def destroy
    @gauchada= Gauchada.find(params[:id])
      flash[:notice] = "Gauchada eliminada"
      @gauchada.destroy
    redirect_to(gauchadas_path)
  end

  def misgauchadas
       @gauchadas=Gauchada.where(user_id: current_user.id) 
  end


  def mispostulaciones
    @postulaciones=Postulacion.where(user_id: current_user.id)
    @gauchadas=Gauchada.all
  end

  def buscar
   @gauchadas = Gauchada.search(params[:search]).order("created_at DESC")
    if @gauchadas.present?
      render 'buscar'
    else
      flash[:notice] = "No se encontraron gauchadas que coincidan con su busqueda"
      redirect_to (gauchadas_path)
    end
  end
  def marcar
    @gauchada= Gauchada.find(params[:id])
    @gauchada.cumplida=true
    if @gauchada.save
        flash[:notice] = "Gauchada marcada como cumplida"
        redirect_to @gauchada
    else
        flash[:notice] = "No se pudo marcar la gauchada como cumplida"
        redirect_to @gauchada
    end
  end

  def cumplidas
    @postulaciones = current_user.postulacions.where(estado: 'Aceptada')
  end

  def calificar
      @gauchada= Gauchada.find(params[:id])
       @gauchada.calificacion = params[:gauchada][:calificacion]
       @gauchada.comentariocal = params[:gauchada][:comentariocal]
       p=@gauchada.postulacions.where(estado: 'Aceptada') [0]
       user=User.find(p.user_id)
       if @gauchada.save
        if(@gauchada.calificacion == "positivo")
          user.puntos_para_gauchadas += 1
          user.puntuacion += 1
        else
          user.puntos_para_gauchadas -= 2
          user.puntuacion -= 2
        end
        user.save
        flash[:notice] = "Gauchada calificada correctamente"
        redirect_to @gauchada
      else
       flash[:notice] = "No se pudo calificar la gauchada"
        redirect_to @gauchada
      end

  end

end

app/helpers/gauchadas_helper.rb
module GauchadasHelper
end

app/views/gauchadas/_formg.html.erb
<%= form_for @gauchada do |g| %>
<div class="form-group">
<%= g.label :titulo %>
<%= g.text_field :titulo,:placeholder=>'Título de la gauchada', class:"form-control" %>
</div>
<div class="form-group">
<%= g.label :descripcion %>
</div>
<div class="form-group">
<%= g.text_area :descripcion,:placeholder=>'Descripción de la gauchada', class:"form-control" %>
</div>
<div class="form-group">
<%= g.label :ubicacion %>
<%= g.text_field :ubicacion,:placeholder=>'Ubicación de la gauchada', class:"form-control" %>
</div>
<div class="form-group">
<%= g.label :imagen %>
<%= g.url_field :imagen,:placeholder=>'URL de la imagen', class:"form-control" %>
</div>
<%= g.submit 'Guardar',:class=>'btn btn-warning' %>
<% end %>

app/views/gauchadas/buscar.html.erb
<% @gauchadas.each do |gauchada| %>
<div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
          <div class="well product-item">
            <div class="pi-img-wrapper">
              <% if (gauchada.imagen != nil) && (gauchada.imagen != "") %>
               <%=image_tag gauchada.imagen,size:"300x300", class:"img-responsive" %>
               <% else %>
               <img src="http://mgiep.unesco.org/wp-content/plugins/ajax-search-lite/img/default.jpg" size="300x300" class="img-responsive">
               <%end %>
            </div>
            <h3><%=  link_to gauchada.titulo, gauchada %></h3>
            <div class="pi-price"> <%= gauchada.ubicacion.titleize %></div>
          </div>
      </div>
      <div class="col-md-4"></div>
</div>
<% end %>

app/views/gauchadas/cumplidas.html.erb
  <% verifico=false %>
  <% @postulaciones.each do |post| %>
    <% gauchada = post.gauchada %>
    <% if (post.gauchada.cumplida == true)%>
      <%verifico=true%>    
    <div class="row">
         <div class="col-md-4"></div>
          <div class="col-md-4">
              <div class="well product-item">
                <div class="pi-img-wrapper">
                  <% if (gauchada.imagen != nil) && (gauchada.imagen != "") %>
                   <%=image_tag gauchada.imagen,size:"300x300", class:"img-responsive" %>
                   <% else %>
                   <img src="http://mgiep.unesco.org/wp-content/plugins/ajax-search-lite/img/default.jpg" size="300x300" class="img-responsive">
                  <%end %>
                </div>
                <h3><%=  link_to gauchada.titulo, gauchada %></h3>
                <div class="pi-price"> <%= gauchada.ubicacion.titleize %></div>
              </div>
         </div>
         <div class="col-md-4"></div>
    </div>
  <% end %>
  <% end %>
    <% if verifico == false %>
      <h3  ALIGN=CENTER> <td colspan="3"> No Tiene Guachadas cumplidas </h3>
   <% end %>

app/views/gauchadas/edit.html.erb
<div class="row">
 <div class="col-md-6 col-md-offset-3">

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Edición de gauchada</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4"></div>
<div class="col-md-4"><%= render 'formg' %></div>

</div>

app/views/gauchadas/index.html.erb
<% @gauchada=Gauchada.all %>
  <% @gauchada.each do |gauchada| %>
  <% if gauchada.cumplida==false %>
  <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="well product-item">
              <div class="pi-img-wrapper">
                <% if (gauchada.imagen != nil) && (gauchada.imagen != "")%>
                   <%=image_tag gauchada.imagen,size:"300x300", class:"img-responsive" %>
                 <% else %>
                   <img src="http://mgiep.unesco.org/wp-content/plugins/ajax-search-lite/img/default.jpg" size="300x300" class="img-responsive">
                 <%end %>
              </div>
              <h3><%=  link_to gauchada.titulo, gauchada %></h3>
              <div class="pi-price"> <%= gauchada.ubicacion %></div>
             </div>
        </div>
        <div class="col-md-4"></div>
  </div>
  <%end%>
<% end %>

	<% if @gauchadas.size == 0 %>
		 <h3> <p  ALIGN=CENTER> <td colspan="3"> No hay gauchadas en este momento </p> </h3>
	<% end %>

app/views/gauchadas/misgauchadas.html.erb
  <% @gauchadas.each do |gauchada| %>
  <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="well product-item">
              <div class="pi-img-wrapper">
                <% if (gauchada.imagen != nil) && (gauchada.imagen != "") %>
                 <%=image_tag gauchada.imagen,size:"300x300", class:"img-responsive" %>
                 <% else %>
                 <img src="http://mgiep.unesco.org/wp-content/plugins/ajax-search-lite/img/default.jpg" size="300x300" class="img-responsive">
                 <%end %>
              </div>
              <h3><%=  link_to gauchada.titulo, gauchada %></h3>
              <div class="pi-price"> <%= gauchada.ubicacion.titleize %></div>
            </div>
        </div>
        <div class="col-md-4"></div>
  </div>

<% end %>
	<% if @gauchadas.size == 0 %>
		<h3  ALIGN=CENTER> <td colspan="3"> No tiene gauchadas </h3>
	<% end %>

app/views/gauchadas/mispostulaciones.html.erb
  <%verif=false%>
  <% @postulaciones.each do |postulacion| %>
  <% pos = postulacion.gauchada_id %>
    <% gauchada = @gauchadas.find(pos) %>
    <% if (gauchada.cumplida == false)%>
    <%verif=true%>
    <div class="row">
         <div class="col-md-4"></div>
          <div class="col-md-4">
              <div class="well product-item">
                <div class="pi-img-wrapper">
                  <% if (gauchada.imagen != nil) && (gauchada.imagen != "") %>
                   <%=image_tag gauchada.imagen,size:"300x300", class:"img-responsive" %>
                   <% else %>
                   <img src="http://mgiep.unesco.org/wp-content/plugins/ajax-search-lite/img/default.jpg" size="300x300" class="img-responsive">
                  <%end %>
                </div>
                <h3><%=  link_to gauchada.titulo, gauchada %></h3>
                <div class="row">
                <div class="pi-price col-md-8"> <%= gauchada.ubicacion.titleize %></div>
                <div class=" pi-price col-md-4"> <h5> <%= postulacion.estado %> </h5> </div>
              </div>
            </div>
         </div>
         <div class="col-md-4"></div>
    </div>
  <% end %>
  <% end %>
  <% if verif == false %>
	 	<h3  ALIGN=CENTER> <td colspan="3"> No Tiene Postulaciones </h3>
  <% end %>

app/views/gauchadas/new.html.erb
<div class="row">
 <div class="col-md-6 col-md-offset-3">

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Nueva Gauchada</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4"></div>
<div class="col-md-4"><%= render 'formg' %></div>
</div>
</div>

app/views/gauchadas/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% usuario=User.find(@gauchada.user_id) %>
    <% if Logro.count==1 %>
      <% @l=Logro.all[0] %>
    <%else%>
    <% @logro=Logro.all %>
    <% @l=@logro[0] %>
    <% @logro.each do |logro| %>
    <% if logro.puntuacion <= usuario.puntuacion %>
        <% @l=logro %>
        <% end %>
    <% end %>
    <%end %>
<div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                      <% if usuario.imagen != nil %>
                          <%= image_tag usuario.imagen, size:"150x200", class: "img-rounded img-responsive"%>
                      <% else %>
                       <img src="http://static.topixcdn.com/pics/user_avatar_empty.png" alt="" class="img-rounded img-responsive" >
                       <% end %>
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%= usuario.nombre %></h4>
                        <small><cite><font color="#f0ad4e"><%=@l.estado %></font> </cite></small>
                    </div>
                </div>
            </div>
        </div>
    </div>
  <div class="row">
    <div class="col-md-12 ">
    <% if user_signed_in? and current_user.id == @gauchada.user_id %>
      <% if @gauchada.postulacions.any? == false %>
          <p>Todavía no hay postulaciones</p>
      <% else %>

        <table class="table table-striped" >
        	<tr>
        		<th> Usuario </th>
            <th> Reputación </th>
        		<th> Fecha de realización </th>
            <th> Comentario </th>
        		<th> Acciones </th>
        	</tr>
        <tr>

          <% @gauchada.postulacions.each do |post| %>
          <% us=User.find(post.user_id) %>
      		<td> <%= us.nombre %></td>
      		<td><% if Logro.count==1 %>
                <% @repu= Logro.find(1) %>
              <%else%>
              <% @log=Logro.all %>
                <% @log.each do |logr| %>
          <% if logr.puntuacion <= us.puntuacion %>
              <% @repu=logr %>
            <% end %>
          <% end %>
          <%end %>
          <cite><font color="#f0ad4e"><%= @repu.estado %></font> </cite>
          </td>
          <td> <%= post.fechaderealizacion %> </td>
         <td ><%= post.comentarios %></td>
      		<td> <% if post.estado == "Esperando" %>
              <%= link_to "Aceptar", postulacion_aceptar_path(id:post.id), class: 'btn btn-block btn-warning' %>
    				  <%= link_to "Rechazar", postulacion_rechazar_path(id:post.id), class: 'btn btn-block btn-danger' %>
              <%else %>
                <cite><font color="#f0ad4e"><%=post.estado %></font> </cite>
              <% end %>
      		</td>
      	</tr>
          <%end%>
      </table>

      <% end %>
    <%end %>
  </div>
  </div>

  </div>
                <div class="col-md-6 text-center">
                    <div class="box">
                        <div class="box-content">
                            <h1 class="tag-title"><%= @gauchada.titulo %></h1>
                            <hr />
                            <% if (@gauchada.imagen != nil) && (@gauchada.imagen != "")%>
                            <p ALIGN=CENTER><%= image_tag @gauchada.imagen, size:"600x400"%></p>
                            <% else %>
                            <p ALIGN=CENTER><img src="http://mgiep.unesco.org/wp-content/plugins/ajax-search-lite/img/default.jpg" size="300x300" class="img-responsive"></p>
                            <%end %>
                            <p><%= @gauchada.descripcion %></p>
                            <br />
                            <% if @gauchada.cumplida %>
                              <h6> La gauchada se encuentra cumplida </h6>
                              <% if @gauchada.calificacion == nil %>
                                <% if @gauchada.user_id == current_user.id %>
                                  <%= form_for @gauchada, url: calificar_gauchada_path, method: :post do |g| %>
                                  <div class="form-group">
                                  <%= "Calificar Gauchada" %>
                                  </div>
                                  <div class="form-group">
                                  <%= "Positivo" %>
                                  <% g.label :calificacion %>
                                  <%= g.radio_button :calificacion, 'positivo', checked: true %>
                                  <%= "Negativo" %>
                                  <% g.label :calificacion %>
                                  <%= g.radio_button :calificacion, 'negativo' %>
                                  <% g.label :comentariocal %>
                                  <%= g.text_area :comentariocal,:placeholder=>'Comentarios Sobre El Postulante. ¿Fue Amable? ¿Cumplio Con Todo?', class:"form-control"  %>
                                  </div>
                                  <%= g.submit 'Guardar', data: {confirm: "¿Estas seguro?"} , :class=>'btn btn-warning' %>
                                  <%end%>
                                  <%end%>
                                  <% if @gauchada.postulacions[0] != nil && @gauchada.postulacions[0].user_id == current_user.id %>
                                    <h6> Todavia no te calificaron </h6>
                                  <%end%>
                              <%else%>
                                <% if @gauchada.user_id == current_user.id %>
                                  <div class="container-fluid">
                                  <%= "Calificaste " +  @gauchada.calificacion %>
                                  </div>
                                  <div class="container-fluid">
                                  <% if @gauchada.comentariocal != "" %>
                                  <%= "Tu comentario: " + @gauchada.comentariocal %>
                                  </div>
                                  <%end%>
                                  <%end%>
                                  <%end%>
                                <% if @gauchada.postulacions[0] != nil && @gauchada.postulacions[0].user_id == current_user.id %>
                                    <div class="container-fluid">
                                    <%= "Te calificaron " +  @gauchada.calificacion %>
                                    </div>
                                    <div class="container-fluid">
                                    <% if @gauchada.comentariocal != nil %>
                                    <%= "Comentario: " + @gauchada.comentariocal %>
                                    </div>
                                    <%end%>
                                  <%end%>
                            <%else %>
                                <h6> La gauchada no se encuentra cumplida </h6>

                                <% if user_signed_in? and current_user.id == @gauchada.user_id %>
                                  <td>
                                  <% if !(@gauchada.postulacions.where(estado:"Aceptada").any?) %>
                                    <%= link_to "Editar", edit_gauchada_path(@gauchada),  class: "btn btn-block btn-warning" %>
                                    <%= link_to "Eliminar", @gauchada, method: :delete, data: {confirm: "¿Estas seguro?"} ,  class: "btn btn-block btn-danger" %>
                                  <% else %>
                                    <%= link_to "Marcar como realizada", realizar_path(:id =>@gauchada.id ), class: "btn btn-block btn-success" %>
                                    <%end%>
                                  </td>
                                <% else %>
                                   <% if user_signed_in? && @gauchada.postulacions.where(user:current_user).any? %>
                                      <% if @gauchada.postulacions.where(user:current_user)[0].estado == "Esperando" %>
                                       <%= link_to "Eliminar postulacion", @gauchada.postulacions.where(user:current_user)[0], method: :delete, class: 'btn btn-block btn-danger' %>
                                       <%else%>
                                            <% if @gauchada.postulacions.where(user:current_user)[0].estado == "Rechazada" %>
                                              <h5> Tu postulación ha sido rechazada </h5>
                                            <%else%>
                                                <h5> Tu postulación fue aceptada! En tu mail podrás encontrar los datos de contacto del usuario</h5>
                                            <%end%>
                                       <%end%>
                                    <% else %>
                                      <% if user_signed_in? && !(@gauchada.postulacions.where(estado:"Aceptada").any?) %>
                                       <%= link_to "Postularse", new_postulacion_path(gauchadaid:@gauchada), class: 'btn btn-block btn-warning' %>
                                       <% else %>
                                          <h6> Ya se ha aceptado una postulación para esta gauchada. </h6>
                                       <% end %>
                                    <% end %>
                                <% end %>
                              <% end %>

                    </div>
                  </div>
                  <hr />
                  <div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-warning">
        <div class="panel-heading">
          Comentarios
        </div>
        <div class="panel-body comments">
                  <% if user_signed_in? && !(@gauchada.cumplida) && !(@gauchada.postulacions.where(estado:"Aceptada").any?)  %>
                   <% if !(@gauchada.user_id == current_user.id) %>
                    <%= form_tag '/comentario' do %>
                    <div class="form-group">
                      <%= hidden_field_tag :gauchada_id, @gauchada.id %>
                      <%= label_tag :cuerpo, 'Nuevo comentario' %>
                      <%= text_area_tag :cuerpo, params[:cuerpo], placeholder: 'Comentario', required: true, class:"form-control" %>
                    </div>
                    <%= submit_tag 'Enviar',:class=>'btn btn-warning' %>
                  <% end %>
                  <% end %>
                  <% else %>
                  <% if !(@gauchada.cumplida) && !(@gauchada.postulacions.where(estado:"Aceptada").any?) %>
                    <h5> Debes <%= link_to "Iniciar sesión", new_user_session_path %> para poder realizar comentarios </h5>
                  <% end %>
                  <% end %>
				  <% if @gauchada.pregunta.size == 0 %>
                    <h4> No hay comentarios aun para esta gauchada </h4>
                  <% else %>
          <div class="clearfix"></div>
          <hr>
		    <% @gauchada.pregunta.order(:created_at).reverse_order.each do |c| %>
                <% user=User.find(c.user_id) %>
          <ul class="media-list">
            <li class="media">
              <div class="comment">
                <a href="#" class="pull-left">
                  <% if user.imagen != nil %>
                          <%= image_tag user.imagen, size:"50x75",  class: "img-circle"%>
                      <% else %>
                       <img src="http://static.topixcdn.com/pics/user_avatar_empty.png" alt="" height="75" width="75" class="img-circle" >
                       <% end %>
                </a>
                <div class="media-body">
                  <strong class="text-warning"><%= user.nombre %></strong>
                  <span class="text-muted">
                  <small class="text-muted"><%= c.fecha %></small>
                  </span>
                  <p>
                    <%= c.cuerpo %>
                  </p>
                </div>
                <div class="clearfix"></div>
              </div>
			  <% if c.respuesta == nil %>
                        <% if user_signed_in? && @gauchada.user_id == current_user.id %>
                        <%= form_tag '/respuesta' do %>
                        <div class="form-group">
                          <%= hidden_field_tag :id, c.id %>
                          <%= label_tag :respuesta, 'Responder' %>
                          <%= text_area_tag :respuesta, params[:respuesta], placeholder: 'Respuesta', required: true, class:"form-control" %>
                        </div>
                        <%= submit_tag 'Enviar',:class=>'btn btn-warning' %>
                        <% end %>
                        <%end %>
                      <% else %>
              <ul class="media-list">
                <li class="media">
                  <div class="comment">
                    <a href="#" class="pull-left">
                      <% if usuario.imagen != nil %>
                              <%= image_tag usuario.imagen, size:"50x75",  class: "img-circle"%>
                          <% else %>
                           <img src="http://static.topixcdn.com/pics/user_avatar_empty.png" alt="" height="75" width="75" class="img-circle" >
                           <% end %>
                    </a>
                    <div class="media-body">
                      <strong class="text-warning"> <%=usuario.nombre %></strong>
                      <p>
                        <%= c.respuesta %>
                      </p>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </li>
                </ul>
				<%end %>

          </ul>

                  <% end %>
                  <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

                  </div>

</div>