config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  devise_for :users
  resources :logros
  resources :postulacions

  resources :gauchadas
  resources :preguntums
  resources :preguntas
  get '/misgauchadas', to: 'gauchadas#misgauchadas'

  resources :gauchadas do
    post "calificar", on: :member
    get "misgauchadas", on: :collection
  end
  get '/mispostulaciones', to: 'gauchadas#mispostulaciones'
  get '/gauchadascumplidas', to: 'gauchadas#cumplidas'

  get '/realizar', to: 'gauchadas#marcar'
  root 'gauchadas#index'
  get '/comprar_puntos/edit', to: 'comprar_puntos#edit'
  get '/comprar_puntos/actualizar', to: 'comprar_puntos#actualizar'
  get '/buscar', to: 'gauchadas#buscar'
  get '/postulacion/aceptar', to: 'postulacions#aceptar'
  get '/postulacion/rechazar', to: 'postulacions#rechazar'
  get '/reporteusuario', to: 'comprar_puntos#reporteusuario'
  get '/reporteganancia', to: 'comprar_puntos#reporteganancia'
  get '/buscarpagos', to: 'comprar_puntos#buscarpagos'
  post '/comentario', to: 'pregunta#create'
  post '/respuesta', to: 'pregunta#responder'

end

app/models/logro.rb
class Logro < ActiveRecord::Base
	validates :estado, presence: true, uniqueness: true
	validates :puntuacion, presence: true, uniqueness: true
	default_scope -> { order("puntuacion") }
end

app/controllers/logros_controller.rb
class LogrosController < ApplicationController

  def index
  end


  def destroy
		if(Logro.count==1)
			flash[:notice] = "No se pudo eliminar el logro: Debe existir al menos un logro en todo momento"
		else
			@logro= Logro.find(params[:id])
  		flash[:notice] = "Logro eliminado"
  		@logro.destroy
		end
    redirect_to(logros_path)
  end


  def show
	@logro = Logro.find(params[:id])
  end


  def new
	@logro = Logro.new

  end



  def create
	@logro= Logro.new(params.require(:logro).permit(:estado, :puntuacion))
 	if @logro.save
   		flash[:notice] = "Logro creado correctamente"
   		redirect_to (logros_path)
	else
   		flash[:notice] = "No se pudo crear el logro"
   		render 'new'
	end
  end


  def edit
	@logro= Logro.find(params[:id])
  end


  def update
  	@logro= Logro.find(params[:id])
    if @logro.update_attributes(params.require(:logro).permit(:estado, :puntuacion))
     	flash[:notice] = "Logro modificado correctamente"
   		redirect_to (logros_path)
    else
    	flash[:notice] = "No se pudo modificar el logro"
   		render 'edit'
    end
  end
end

app/helpers/logros_helper.rb
module LogrosHelper
end

app/views/logros/_form.html.erb
<%= form_for @logro do |f| %>
<div class="form-group">
<%= f.label :estado %>
<%= f.text_field :estado,:placeholder=>'Nombre del logro', class:"form-control" %>
</div>
<div class="form-group">
<%= f.label :puntuación %>
<%= f.number_field :puntuacion , class:"form-control"%>
</div>
<%= f.submit 'Guardar',:class=>'btn btn-warning' %>

<% end %>

app/views/logros/edit.html.erb
<div class="row">
 <div class="col-md-6 col-md-offset-3">

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Edición del logro</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4"></div>
        <div class="col-md-4"><%= render 'form' %></div></div>
</div>
</div>
</div>

app/views/logros/index.html.erb
<h1>Logros</h1>
<h1> <%= link_to "Nuevo Logro", new_logro_path, class: 'btn btn-warning btn-sm' %> </h1>
<table class="table table-striped">
	<tr>
		<th> Estado </th>
		<th> Puntuacion </th>
		<th> Acciones </th>



	</tr>
	<% Logro.all.each do |logros| %>
	<tr>

		<td> <%= logros.estado%>  </td>
		<td> <%= logros.puntuacion%>  </td>
		<td>
				<%= link_to "Editar", edit_logro_path(logros), class: 'btn btn-warning btn-sm' %>
				<%= link_to "Eliminar", logros, method: :delete, class: 'btn btn-danger btn-sm' %>
		</td>
	</tr>

<% end %>
</table>

app/views/logros/new.html.erb
<div class="row">
 <div class="col-md-6 col-md-offset-3">

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Nuevo logro</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4"></div>
        <div class="col-md-4"><%= render 'form' %></div></div>
</div>
</div>
</div>

app/views/logros/show.html.erb
<h1>Logro</h1>
<h1> <%= link_to "Nuevo Logro", new_logro_path, class: 'btn btn-info btn-sm' %> </h1>
<table class="table table-striped">	
	<tr>
		<th> Estado </th>
		<th> Puntuacion </th>
			
	</tr>
	<tr>

		<td> <%= @logro.estado%>  </td>
		<td> <%= @logro.puntuacion%>  </td>
		
	</tr>

</table>