config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  devise_for :users
  resources :logros
  resources :postulacions

  resources :gauchadas
  resources :preguntums
  resources :preguntas
  get '/misgauchadas', to: 'gauchadas#misgauchadas'

  resources :gauchadas do
    post "calificar", on: :member
    get "misgauchadas", on: :collection
  end
  get '/mispostulaciones', to: 'gauchadas#mispostulaciones'
  get '/gauchadascumplidas', to: 'gauchadas#cumplidas'

  get '/realizar', to: 'gauchadas#marcar'
  root 'gauchadas#index'
  get '/comprar_puntos/edit', to: 'comprar_puntos#edit'
  get '/comprar_puntos/actualizar', to: 'comprar_puntos#actualizar'
  get '/buscar', to: 'gauchadas#buscar'
  get '/postulacion/aceptar', to: 'postulacions#aceptar'
  get '/postulacion/rechazar', to: 'postulacions#rechazar'
  get '/reporteusuario', to: 'comprar_puntos#reporteusuario'
  get '/reporteganancia', to: 'comprar_puntos#reporteganancia'
  get '/buscarpagos', to: 'comprar_puntos#buscarpagos'
  post '/comentario', to: 'pregunta#create'
  post '/respuesta', to: 'pregunta#responder'

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :gauchada
  belongs_to :usuario
  validates :descripcion, presence: true
  validates_associated :usuario
  validates_associated :gauchada
end

app/models/gauchada.rb
class Gauchada < ActiveRecord::Base
  has_many :pregunta
  has_many :postulacions
  has_many :comentarios
  belongs_to :usuario
  validates_associated :usuario
  validates :titulo, presence: true
  validates :descripcion, presence: true
  validates :ubicacion, presence: true
 validates :imagen, format: { with: /.*/ }
  default_scope -> { order("created_at desc") }

def self.search(search)
  where("ubicacion ILIKE ? OR titulo ILIKE ? OR descripcion ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
end
end

app/models/logro.rb
class Logro < ActiveRecord::Base
	validates :estado, presence: true, uniqueness: true
	validates :puntuacion, presence: true, uniqueness: true
	default_scope -> { order("puntuacion") }
end

app/models/pago.rb
class Pago < ActiveRecord::Base
  belongs_to :usuario
end

app/models/postulacion.rb
class Postulacion < ActiveRecord::Base
  belongs_to :gauchada
  belongs_to :user
  validates :comentarios, presence: true  
end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
  belongs_to :gauchada
  belongs_to :usuario
  validates :descripcion, presence: true
  validates_associated :usuario
  validates_associated :gauchada
end

app/models/preguntum.rb
class Preguntum < ActiveRecord::Base
  belongs_to :gauchada
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :gauchadas
   has_many :pregunta
   has_many :postulacions
   has_many :pagos
   def <=>(other)
    other.puntos_para_gauchadas <=> self.puntos_para_gauchadas
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    has_many :gauchadas
    has_many :preguntums
    has_many :pagos
    has_many :comentarios
end

app/controllers/logros_controller.rb
class LogrosController < ApplicationController

  def index
  end


  def destroy
		if(Logro.count==1)
			flash[:notice] = "No se pudo eliminar el logro: Debe existir al menos un logro en todo momento"
		else
			@logro= Logro.find(params[:id])
  		flash[:notice] = "Logro eliminado"
  		@logro.destroy
		end
    redirect_to(logros_path)
  end


  def show
	@logro = Logro.find(params[:id])
  end


  def new
	@logro = Logro.new

  end



  def create
	@logro= Logro.new(params.require(:logro).permit(:estado, :puntuacion))
 	if @logro.save
   		flash[:notice] = "Logro creado correctamente"
   		redirect_to (logros_path)
	else
   		flash[:notice] = "No se pudo crear el logro"
   		render 'new'
	end
  end


  def edit
	@logro= Logro.find(params[:id])
  end


  def update
  	@logro= Logro.find(params[:id])
    if @logro.update_attributes(params.require(:logro).permit(:estado, :puntuacion))
     	flash[:notice] = "Logro modificado correctamente"
   		redirect_to (logros_path)
    else
    	flash[:notice] = "No se pudo modificar el logro"
   		render 'edit'
    end
  end
end

app/controllers/pago_controller.rb
class PagoController < ApplicationController

  def new
  end

  def create
    @pago =Pago.new(params.require(:pago).permit(:monto, :user_id))
    @user =current_user
    @pago.user_id = @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comprar_puntos_helper.rb
module ComprarPuntosHelper
end

app/helpers/gauchadas_helper.rb
module GauchadasHelper
end

app/helpers/logros_helper.rb
module LogrosHelper
end

app/helpers/pago_helper.rb
module PagoHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/posulacion_helper.rb
module PosulacionHelper
end

app/views/enviar_datos/datos_postulante.html.erb
<p>Hola <%= @user.nombre %>!</p>

<p>A continuación te mostramos los datos del postulante que aceptaste para tu gauchada "<%=@gauchada.titulo %>" :</p>

<p>Nombre: <%=@user_postulacion.nombre %> </p>
<p>Email: <%=@user_postulacion.email %> </p>
<% if !(@user_postulacion.telefono == nil) %>
  <p>Telefono:<%=@user_postulacion.telefono %> </p>
<% end %>

<p>Recordá marcar la gauchada como realizada una vez que <%=@user_postulacion.nombre %> la cumpla! Luego vas a tener la opción de calificarlo. </p>
<p>Gracias!</p>
<p>Tus amigos de Gauchada.com</p>

app/views/enviar_datos/datos_usuario.html.erb
<p>Hola <%= @user_postulacion.nombre %>!</p>

<p>El usuario <%= @user.nombre %> aceptó tu postulación para la guachada "<%=@gauchada.titulo %>" ! A continuación te dejamos sus datos para que puedas ponerte en contacto:</p>

<p>Nombre: <%=@user.nombre %> </p>
<p>Email: <%=@user.email %> </p>
<% if !(@user.telefono == nil) %>
  <p>Telefono:<%=@user.telefono %> </p>
<% end %>

<p>Gracias!</p>
<p>Tus amigos de Gauchada.com</p>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="thumbnail" href="/">
        <%= image_tag "logo.png", title: "Logo", class: "img-responsive" %></a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">  <% if user_signed_in? %>
            <li><p class = "navbar-text">Bienvenido/a <strong><%= current_user.nombre %></strong>.</p></li>
            <% if current_user.puntos_para_gauchadas == 1 %>
              <li><p class = "navbar-text">Tenés <strong><%= current_user.puntos_para_gauchadas %> punto</strong> para pedir gauchadas</p></li>
             <%else%>
                <li><p class = "navbar-text">Tenés <strong><%= current_user.puntos_para_gauchadas %> puntos</strong> para pedir gauchadas</p></li>
             <%end%>
            <li><a href="/gauchadas/new"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Nueva gauchada</a></li>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-collapse-down" aria-hidden="true"></span> Opciones <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Ver mis gauchadas', misgauchadas_path, :class => 'navbar-link' %></li>
                <li><%= link_to 'Ver mis postulaciones', mispostulaciones_path, :class => 'navbar-link' %></li>
                <li><%= link_to 'Ver gauchadas cumplidas', gauchadascumplidas_path, :class => 'navbar-link' %></li>
                <li><%= link_to 'Configuración', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><a href="/comprar_puntos/edit">Comprar puntos</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              </ul>
            </li>
          <% else %>
            <li><button type="submit" class="btn"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>   <%= link_to "Iniciar sesión", new_user_session_path, :class => 'navbar-link '  %></button></li>
            <li><button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><%= link_to "¿No tenés cuenta? ¡Registrate!", new_user_registration_path, :class => 'navbar-link'  %> </button></li>
          <% end %>



        </ul>
        <%= form_tag '/buscar', :method => "get", id: "search-form", class:"navbar-form navbar-left" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar gauchadas", class:"form-control" %>
        <%= submit_tag "Buscar" , class:'btn btn-warning' %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? and current_user.administrador == true %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-collapse-down" aria-hidden="true"></span> Opciones admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li> <a href="/logros"> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Ver Logros </a> </li>
            <li> <a href="/reporteusuario"> <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> Reporte de usuario </a> </li>
            <li> <a href="/reporteganancia"> <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> Reporte de ganancias </a> </li>
            </ul>
            </li>
          <% end %>
            </li>
            </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  </header>

app/views/layouts/application.html.erb

<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="http://www.iconj.com/ico/k/x/kx5bc3q0j6.ico" type="image/x-icon" />
  <title>Gauchada</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>


<div class="container">

  <%= image_tag "header.png", title: "Header", class: "img-responsive" %>


  <% if flash[:alert] %>
    <div class="alert alert-warning"> <%= flash[:alert] %> </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-warning"> <%= flash[:notice] %> </div>
  <% end %>

  <%= yield %>

</div>

</body>
</html>